packages/compiler-vapor/__tests__/__snapshots__/compile.test.ts.snap
packages/compiler-vapor/__tests__/compile.test.ts
packages/compiler-vapor/src/transform.ts

feat: implement error handling for v-html

---

packages/compiler-vapor/__tests__/__snapshots__/compile.test.ts.snap
packages/compiler-vapor/__tests__/compile.test.ts

close #35 
This is a unit test PR related to the complex expression parsing of v-bind in Vue Vapor.
In addition to complex expressions, I also added some other tests related to `v-bind`.
I referred to the existing tests related to `v-bind` in `/packages/compiler-core` when adding these tests.

test: compound expression for `v-bind`

---

packages/compiler-vapor/__tests__/__snapshots__/compile.test.ts.snap
packages/compiler-vapor/__tests__/compile.test.ts
packages/compiler-vapor/src/generate.ts
packages/compiler-vapor/src/ir.ts
packages/compiler-vapor/src/transforms/transformElement.ts
packages/runtime-core/src/index.ts
packages/runtime-vapor/src/directives.ts
playground/src/directive.vue

close: #33 
`<div v- example:foo.bar = 'text'>`
`_withDirectives(n1, [[_ctx.vExample, _ctx.msg, \\"foo\\", { bar: true }]])`
Dynamic parameters need to wait for the `genExpression` and instruction update life cycles to be completed before they can be implemented.

feat(compiler-vapor): support custom directives argument & modifiers

---

packages/compiler-vapor/__tests__/transforms/__snapshots__/vBind.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/vBind.spec.ts
packages/compiler-vapor/src/generate.ts
packages/compiler-vapor/src/ir.ts
packages/compiler-vapor/src/transforms/vBind.ts

close #37
```vue
<svg :view-box.camel="viewBox"></svg>
<svg viewBox="xxx"></svg>
```

feat: camel modifier for `v-bind`

---

packages/compiler-vapor/__tests__/transforms/__snapshots__/vBind.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/vBind.spec.ts

Merge the original codegen tests into the new transform tests

test: combine with transform and codegen tests for `v-bind`

---

playground/setup/dev.js

The commit updates the method of converting URLs to file paths in development setup. Using 'fileURLToPath' from Node's URL module has replaced the earlier approach, enhancing reliability and efficiency of file path resolution.

refactor: improve file path resolution

---

packages/runtime-vapor/src/directive.ts
playground/src/directive.vue

~~TODO: unit test~~
I will rewrite a more complete directive unit test

feat(compiler-vapor): functional custom directive support updated hooks

---

packages/compiler-vapor/__tests__/__snapshots__/compile.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/__snapshots__/vBind.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/__snapshots__/vHtml.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/__snapshots__/vOn.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/__snapshots__/vText.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/vBind.spec.ts
packages/compiler-vapor/__tests__/transforms/vOn.spec.ts
packages/compiler-vapor/src/generate.ts
packages/runtime-vapor/__tests__/apiWatch.spec.ts
packages/runtime-vapor/__tests__/renderWatch.spec.ts
packages/runtime-vapor/src/apiWatch.ts
packages/runtime-vapor/src/errorHandling.ts
packages/runtime-vapor/src/index.ts
packages/runtime-vapor/src/renderWatch.ts
packages/runtime-vapor/src/scheduler.ts

The introduction of a specific Render Watch API is primarily due to these reasons:
1. The Flush mode of the Watch API doesn't satisfy the requirements for rendering scenarios. Initially, in PR #69, we used a method that determined if `watchEffect` was within the render function and treated it uniquely. However, after discussions with Evan You, he proposed using an independent Render Watch API to accomplish this feature.
2. Implementation of Life Cycle Hooks in Vapor mode: The BeforeUpdate and Updated hooks are intimately connected to re-runs of the render function. But in Vapor mode, the render function only runs once during a component's lifecycle. Updating content is divided among each effect; thus implementing BeforeUpdate and Updated hooks requires emitting events when an effect …

feat: renderWatch / renderEffect

---

packages/reactivity/__tests__/baseWatch.spec.ts
packages/reactivity/src/baseWatch.ts
packages/reactivity/src/index.ts
packages/runtime-vapor/__tests__/renderWatch.spec.ts
packages/runtime-vapor/src/component.ts
packages/runtime-vapor/src/directive.ts
packages/runtime-vapor/src/renderWatch.ts
packages/runtime-vapor/src/scheduler.ts
playground/src/App.vue
playground/src/directive.vue

feat(runtime-vapor): lifecycle beforeUpdate and updated hooks

---

packages/compiler-vapor/__tests__/transforms/__snapshots__/vOn.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/vOn.spec.ts
packages/compiler-vapor/src/generate.ts

Before:
```ts
_setText(n1, undefined, _ctx.foo._ctx.bar)
```
After:
```ts
_setText(n1, undefined, _ctx.foo.bar)
```

fix(compiler-vapor): should not prefix member expression

---

packages/runtime-vapor/__tests__/if.spec.ts
packages/runtime-vapor/__tests__/template.spec.ts
packages/runtime-vapor/src/dom.ts
packages/runtime-vapor/src/if.ts
packages/runtime-vapor/src/render.ts
packages/runtime-vapor/src/template.ts

The existing `template` runtime function has some issues when using the `DocumentFragment` API. This PR aims to solve these problems through refactoring.
related info：https://github.com/whatwg/dom/issues/736

refactor(runtime-vapor): template fragment

---

packages/compiler-vapor/__tests__/transforms/__snapshots__/vOn.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/vOn.spec.ts
packages/compiler-vapor/src/generators/expression.ts

I found that some expressions are having issues being parsed in inline mode.
the examples
```vue
<div @click="x=y"/>
<div @click="x++"/>
<div @click="{ x } = y"/>
```
compilation results:
```js
_on(n1, "click", $event => (_unref(x) = _unref(y)))
_on(n2, "click", $event => (_unref(x)++))
_on(n3, "click", $event => ({ _unref(x) } = _unref(y)))
```

feat(compiler-vapor): complex identifier rewriting with vOn

---

packages/compiler-vapor/__tests__/transforms/__snapshots__/transformElement.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/transformElement.spec.ts
packages/compiler-vapor/__tests__/transforms/vBind.spec.ts
packages/compiler-vapor/__tests__/transforms/vOnce.spec.ts
packages/compiler-vapor/src/generators/prop.ts
packages/compiler-vapor/src/ir.ts
packages/compiler-vapor/src/transform.ts
packages/compiler-vapor/src/transforms/transformElement.ts

This PR will support the features of `v-bind` in the code example below.
```vue
<div class="foo" :class="{ bar: isBar }" />
<div style="color: green" :style="{ color: 'red' }" />
```

feat(compiler-vapor): props merging

---

packages/runtime-vapor/__tests__/_utils.ts
packages/runtime-vapor/__tests__/component.spec.ts
packages/runtime-vapor/__tests__/componentEmits.spec.ts
packages/runtime-vapor/__tests__/componentProps.spec.ts
packages/runtime-vapor/__tests__/if.spec.ts
packages/runtime-vapor/__tests__/renderWatch.spec.ts
packages/runtime-vapor/__tests__/vShow.spec.ts
packages/runtime-vapor/src/for.ts
packages/runtime-vapor/src/index.ts

The unit tests in `runtime-vapor` contain a lot of repetitive code related to defining and rendering components. This PR encapsulates them into a single function for reuse.

test(runtime-vapor): refactor duplicate compoent test code

---

packages/runtime-vapor/__tests__/_utils.ts
packages/runtime-vapor/__tests__/componentProps.spec.ts
packages/runtime-vapor/src/component.ts
packages/runtime-vapor/src/componentProps.ts
packages/runtime-vapor/src/render.ts

close #48 
TODO:
~~- [ ] fallthrough attributes~~
-> move to https://github.com/vuejs/core-vapor/issues/125
I felt that the design for Fallthrough Attributes needed some consideration, so I made it a separate issue.

feat(runtime-vapor): component attrs

---

packages/reactivity/src/baseWatch.ts
packages/runtime-vapor/src/scheduler.ts

Optimize `queueJob` when queueing large amount of jobs with the same id (common in v-for under vapor mode).
Benchmark for selecting from 10000 items:
- Before 
- `select: min: 23.30 / max: 29.50 / median: 26.00ms / mean: 26.02ms / time: 24.80ms / std: 2.08 over 10 runs`
- After
- `select: min: 10.90 / max: 18.50 / median: 15.10ms / mean: 14.41ms / time: 15.20ms / std: 2.47 over 10 runs`
- `vuejs/vapor` (reference)
- without memo `select: min: 9.60 / max: 27.80 / median: 19.10ms / mean: 16.54ms / std: 5.87 over 10 runs`
- with memo `select: min: 6.00 / max: 23.30 / median: 8.60ms / mean: 12.58ms / std: 6.51 over 10 runs`

perf: optimize scheduler queueJob performance

---

packages/runtime-vapor/src/for.ts

Incorrect `Array.from` causes `v-for` to be very time-consuming at runtime

perf(runtime-vapor): don't wrap `Array.from` for array in v-for

---

packages/compiler-vapor/__tests__/transforms/__snapshots__/vModel.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/vModel.spec.ts
packages/compiler-vapor/src/generators/expression.ts

Currently, member expressions cannot be used in v-model
```
<div v-model="setupRef.child" />
<div v-model="setupMaybeRef.child" />
```
Wrong generated
```
$event => (setupRef.value = $event.child)
$event => (_isRef(setupMaybeRef) ? (setupMaybeRef.value = $event) : null.child)
```
This PR will fix this issue
```
$event => (setupRef.value.child = $event)
$event => (_unref(setupMaybeRef).child = $event)
```

fix(compiler-vapor): member expression with assignment

---

packages/compiler-vapor/src/transforms/transformRef.ts

Currently, ref with the component will cause `setRef` to be called first, resulting in an error.

fix(compiler-vapor): SET_REF operation should be registered last

---

packages/runtime-vapor/__tests__/apiLifecycle.spec.ts
packages/runtime-vapor/src/apiRender.ts

resolve #163 
The mounted flag of the sub-component was not being updated.
I noticed that tests for the apiLifecycle were not implemented, so I created an issue for it.
-> https://github.com/vuejs/core-vapor/issues/164

fix(runtime-vapor): trigger updated hooks across components

---

packages/runtime-vapor/__tests__/apiSetupHelpers.spec.ts
packages/runtime-vapor/src/apiSetupHelpers.ts
packages/runtime-vapor/src/index.ts
playground/src/sub-comp.vue

feat(runtime-vapor): setup helpers useAttrs & useSlots

---

packages/compiler-vapor/__tests__/transforms/__snapshots__/transformElement.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/transformElement.spec.ts
packages/compiler-vapor/src/generators/component.ts
packages/compiler-vapor/src/generators/event.ts
packages/compiler-vapor/src/generators/prop.ts
packages/compiler-vapor/src/transform.ts
packages/compiler-vapor/src/transforms/vOn.ts

Currently, in `<Foo @bar="handleBar($event)">` this case, compiler will prefix `$event` with `_ctx`  wrongly.

fix(compiler-vapor): v-on for component support `$event` argument

---

packages/runtime-vapor/__tests__/dom/prop.spec.ts
packages/runtime-vapor/__tests__/renderEffect.spec.ts
packages/runtime-vapor/src/apiLifecycle.ts
packages/runtime-vapor/src/apiRender.ts
packages/runtime-vapor/src/component.ts
packages/runtime-vapor/src/componentLifecycle.ts
packages/runtime-vapor/src/componentProps.ts
packages/runtime-vapor/src/renderEffect.ts

The existing `setCurrentInstance` will set `instance.scope.on()` internally and `instance.scope.off()` when calling reset, but as an internal Function, this hidden behavior is not very intuitive, and there are two problems:
1. `effectScope.on` cannot handle nested recursive calls to itself, because the internal `prevScope` can only store one value.
2. Not all situations that need to set `currentInstance` need to set `instance.scope.on()` at the same time, and this behavior is wrong in `renderEffect`.
So this PR removes `instance.scope.on()` in `setCurrentInstance`.
I initially started investigating this issue because of the following bug.
[Bug Playground](https://vapor-repl.netlify.app/#__VAPOR__eNp9UcFu1DAQ/ZWROXhX2iaq4LRKgwD1AAdAgLhgDiGZJC6ObdlOWBTl3xk77DatqkaKZL/3ZvzmzczeWJtNI7IjK3ztpA3 …

fix(runtime-vapor): detach effect scope & component instance

---

packages/runtime-vapor/__tests__/componentExpose.spec.ts
packages/runtime-vapor/src/component.ts

feat(runtime-vapor): implement expose

---

packages/runtime-vapor/__tests__/apiExpose.spec.ts
packages/runtime-vapor/__tests__/dom/templateRef.spec.ts
packages/runtime-vapor/src/component.ts
packages/runtime-vapor/src/dom/templateRef.ts

impl ref on component close #184

feat(runtime-vapor): template ref on component

---

packages/compiler-vapor/__tests__/transforms/__snapshots__/transformElement.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/__snapshots__/vModel.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/transformElement.spec.ts
packages/compiler-vapor/__tests__/transforms/vModel.spec.ts
packages/compiler-vapor/src/generators/component.ts
packages/compiler-vapor/src/generators/prop.ts
packages/compiler-vapor/src/generators/utils.ts
packages/compiler-vapor/src/ir.ts
packages/compiler-vapor/src/transforms/transformElement.ts

Related: base #4, props #25, emits #41, v-model #180
Example
```vue
<Comp :[name]="value" @[name2]="value2" v-model:[name3]="value3" />
```

feat(compiler-vapor):  component with dynamic arguments

---

packages/compiler-vapor/__tests__/transforms/__snapshots__/transformSlotOutlet.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/transformSlotOutlet.spec.ts

update snapshot for transformSlotOutlet.spec.ts.snap
add tests for default slot outlet with props & fallback
add tests for named slot outlet with props & fallback

test(runtime-vapor): slot outlets with props & fallbacks

---

packages/compiler-vapor/__tests__/transforms/__snapshots__/vOnce.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/vOnce.spec.ts
packages/compiler-vapor/src/generators/if.ts
packages/compiler-vapor/src/ir.ts
packages/compiler-vapor/src/transforms/vIf.ts
packages/runtime-vapor/src/apiCreateIf.ts

Implemented basic v-once support for v-if/else via a **once** flag, please review and advise if any scenarios are unaddressed.

feat: v-once support for v-if/else via a once flag

---

packages/runtime-vapor/src/component.ts
packages/runtime-vapor/src/componentSlots.ts
packages/runtime-vapor/src/renderEffect.ts
packages/runtime-vapor/src/scheduler.ts
packages/runtime-vapor/src/warning.ts

the [optional chaining (?.)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) has [bigger bundle size](https://esbuild.github.io/try/#dAAwLjIxLjEALS10YXJnZXQ9ZXMyMDE5AGE/LmI/LmM)

refactor(runtime-vapor): remove optional chaining syntax

---

package.json
packages/vue-vapor/__tests__/e2e/e2eUtils.ts
packages/vue-vapor/__tests__/e2e/todomvc.spec.ts
packages/vue-vapor/examples/composition/todomvc.html
playground/src/example-todomvc.vue
vitest.e2e.config.ts

Resolved #109 
wait for #211 #123

test(vue-vapor): todomvc e2e test

---

packages/runtime-vapor/__tests__/apiLifecycle.spec.ts
packages/runtime-vapor/src/index.ts

resolve #164 
relates: #183 
---
Regarding the lifecycle hook, I wrote tests based on the cases in packages/runtime-core/__tests__/apiLifecycle.spec.ts, but there seem to be some points where the behavior is incorrect. 
I added FIXME to the test cases and created an issue on https://github.com/vuejs/core-vapor/issues/216.

test(runtime-vapor): api lifecycle hooks

---

packages/reactivity/src/effectScope.ts
packages/runtime-vapor/__tests__/directives/vShow.spec.ts
packages/runtime-vapor/__tests__/for.spec.ts
packages/runtime-vapor/__tests__/if.spec.ts
packages/runtime-vapor/src/apiCreateFor.ts
packages/runtime-vapor/src/apiCreateIf.ts
packages/runtime-vapor/src/blockEffectScope.ts
packages/runtime-vapor/src/component.ts
packages/runtime-vapor/src/componentLifecycle.ts
packages/runtime-vapor/src/directives.ts
packages/runtime-vapor/src/directivesChildFragment.ts
packages/runtime-vapor/src/renderEffect.ts

new item:           `created` -> `beforeMount` -> `mounted`
other everyone: `beforeUpdate` -> `updated`
all events:           `beforeUpdate` -> `created` -> `beforeMount` -> `updated` -> `mounted`
removed item:    `beforeUnmount` -> `unmounted`
other everyone: `beforeUpdate` -> `updated`
all events:           `beforeUpdate` -> `beforeUnmount` -> `updated` -> `unmounted`
everyone: `beforeUpdate` -> `updated`
I've created new `BlockEffectScope` and `createChildFragmentDirectives` APIs that I hope will help make it easier to implement Lifecycle Hooks in Vapor. such as the lifecycle in slots or in components

feat: directive lifecycle hooks in `v-for`, `v-if` and component

---

packages/compiler-vapor/__tests__/transforms/__snapshots__/transformTemplateRef.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/__snapshots__/vFor.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/__snapshots__/vOnce.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/vFor.spec.ts
packages/compiler-vapor/src/generate.ts
packages/compiler-vapor/src/generators/block.ts
packages/compiler-vapor/src/generators/for.ts
packages/runtime-vapor/__tests__/dom/templateRef.spec.ts
packages/runtime-vapor/__tests__/for.spec.ts
packages/runtime-vapor/src/apiCreateFor.ts
packages/runtime-vapor/src/destructuring.ts
packages/vue-vapor/examples/composition/todomvc.html
playground/src/v-for.js

related #204 closes #220
[TODO List Demo](https://deploy-preview-217--vapor-repl.netlify.app/#__VAPOR__eNp9U81u00AQfpWRqeREMvYBTlZaKLSHcqCoVFwwUh17/NOsd63dsZvI8pErTwAv1ydhdp00LkI9WNqZ+fzNt9/ODN5524Z9h17srUym65bAIHUtiFSWp4lHJvHOElk3rdIEA2SqaTvCPACJW7qts00AGosATJUKoR5u7Jl0XZao3fkhpay6LArMCEYotGrA535+IhOZKWkISOXKwKmlWXwfciUx5kZ9DEUqDMIYsJY1ihj8K0gbSN0PPow/lpZjFU2yWSQHhE0rUkKOAFZ53bsDHx0F9K8LpflWi8HFAYRhqKhCzU1qmeN2CaqYBCUeGNoJZHReGybdxbAWKttwId7gjvOOw9ljW3CTWrI3cAgBaNfa/7MKs81abRPvWIpdEnMuOwGhvXfYzyHvs4rfwBLMEWzUCfYoKaRUl0jhnuj4Z3QUZNpUnsEwwDOGd+A//v7pAzv6+OcXOzlayOQQn19x4MzggN21FHsTI4eZvI0O5q7WHZGSLFfwNNiRsfaFbWeqxeE1+5h0h8eXvLOYk2FCCpQlVeMdjEs28/ziAm6vL66tjGd11jJ14q6raPbQXuA5uWFFjZjN8d79RuWdwNkzARynWSNzfEs55D2Yz2fU2yRP6T//WNgECqP96sxAz/kW/C3DRnWSFv6rtG395dO02tmE2j4/51nc5CdfhQxvRVGX4b1Rkm8zW …

feat: destructuring + nesting in v-for

---

packages/compiler-vapor/__tests__/transforms/__snapshots__/vFor.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/__snapshots__/vSlot.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/vFor.spec.ts
packages/compiler-vapor/__tests__/transforms/vSlot.spec.ts
packages/compiler-vapor/src/generate.ts
packages/compiler-vapor/src/generators/component.ts
packages/compiler-vapor/src/generators/for.ts
packages/compiler-vapor/src/ir.ts
packages/compiler-vapor/src/transforms/vSlot.ts

related #154 
I'll be working on the runtime for v-slot props in another PR later
```vue
<Comp v-slot="{ foo, ...bar }">{{ foo + bar }}</Comp>
<Comp v-slot:named="props">{{ props.foo }}</Comp>
<Comp>
<template #default="{ foo }">
<Inner v-slot="{ bar }">
{{ foo + bar + baz }}
</Inner>
{{ foo + bar + baz }}
</template>
</Comp>
<Comp>
<template v-for="item in list" #[item]="{ bar }">foo</template>
</Comp>
<Comp>
<template v-if="condition" #condition>condition slot</template>
<template v-else-if="anotherCondition" #condition="{ foo, bar }">another condition</template>
<template v-else #condition>else condition</template>
</Comp>
```

feat(compiler-vapor): v-slot props + v-slot on component

---

packages/runtime-vapor/__tests__/componentSlots.spec.ts
packages/runtime-vapor/src/componentSlots.ts
packages/runtime-vapor/src/dom/prop.ts

feat(runtime-vapor): slot props

---

packages/runtime-vapor/src/apiCreateVaporApp.ts
packages/runtime-vapor/src/apiRender.ts
packages/runtime-vapor/src/component.ts
packages/runtime-vapor/src/devtools.ts
packages/runtime-vapor/src/helpers/resolveAssets.ts
packages/runtime-vapor/src/profiling.ts
packages/runtime-vapor/src/warning.ts

feat(runtime-vapor): implement app.config.performance

---

packages/runtime-vapor/__tests__/directives/directives.spec.ts

align directive test case with core

test(runtime-vapor): add directive test case

---

packages/runtime-vapor/src/apiLifecycle.ts
packages/runtime-vapor/src/apiRender.ts
packages/runtime-vapor/src/component.ts
packages/runtime-vapor/src/componentLifecycle.ts
packages/runtime-vapor/src/enums.ts
packages/runtime-vapor/src/errorHandling.ts

fix(runtime-vapor): apiLifeCycle circular dependencies

---

packages/runtime-vapor/__tests__/componentSlots.spec.ts
packages/runtime-vapor/src/componentSlots.ts

related #168
When all slots are static slots, it is also necessary to call `withCtx` to attach the current instance to the slots.

fix(runtime-vapor): current instance is not attached to static slots

---

.github/workflows/ci.yml

I didn't remove the release file completely, for now let's just see if this works by just adding pkg.pr.new! 
Before running the workflows for this PR, the [github app](https://github.com/apps/pkg-pr-new) should be installed! 
Thank you so much @sxzz for the opportunity!

ci: continuous releases with pkg.pr.new

---

packages/runtime-vapor/src/dom/template.ts

[Check the Bench](https://jsbench.me/45lyjycdiu/1)
The old plan (for nextSibling) only has a speed advantage when accessing adjacent elements

perf(runtime-vapor): `children` helper

---

packages/compiler-vapor/src/generators/component.ts
packages/compiler-vapor/src/ir/component.ts

```tsx
<Comp v-slots={{ default: ({ foo })=> <>{ foo }</> }}></Comp>
```

feat(compiler-vapor): support v-slots expression for jsx-vapor

---

benchmark/client/App.vue
benchmark/client/profiling.ts

related #269 
Change to use nextTick to record time consumption because:
1. using `requestIdleCallback` to record time is inaccurate.
2. should mainly focus on the performance loss of the JS Runtime part.

workflow: fix inaccurate test timer in benchmark

---

benchmark/client/index.html
benchmark/index.js

Attempt to reduce Standard Deviation (std) by running the warmup phase of benchmark.
Sadly. the actual effect doesn't look significant on my device.

workflow(benchmark): warmup run

---

packages/runtime-vapor/src/apiCreateFor.ts
packages/runtime-vapor/src/apiRender.ts
packages/runtime-vapor/src/componentLifecycle.ts
packages/runtime-vapor/src/directives.ts
packages/runtime-vapor/src/directives/vModel.ts
packages/runtime-vapor/src/directives/vShow.ts
packages/runtime-vapor/src/index.ts

Simplify custom directive API to match the template ref API.
~~Waiting a formal RFC~~ Internal API currently.
Closes #278

refactor(runtime-vapor): simplify directive mechanism

---

packages/compiler-vapor/__tests__/transforms/__snapshots__/vFor.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/__snapshots__/vOnce.spec.ts.snap
packages/compiler-vapor/src/generators/for.ts
packages/compiler-vapor/src/ir/index.ts
packages/compiler-vapor/src/transforms/vFor.ts
packages/runtime-vapor/src/apiCreateFor.ts
packages/runtime-vapor/src/memo.ts
packages/runtime-vapor/src/renderEffect.ts

Closes #18
Drop `v-memo` in Vapor, since it's useless for performance.

refactor(vapor): drop memo

---

packages/runtime-vapor/src/apiRender.ts

Skip [the type check](https://github.com/vuejs/vue-vapor/blob/e61cedf3fdac8770540198bca077ae3ae1bf5cbd/packages/runtime-vapor/src/apiRender.ts#L58-L64) for production since this is only for Dev HMR

perf(runtime-vapor): `setup()` returning object is only needed in __DEV__ (HMR)

---

packages/compiler-vapor/__tests__/__snapshots__/compile.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/__snapshots__/vBind.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/__snapshots__/vFor.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/__snapshots__/vOnce.spec.ts.snap
packages/compiler-vapor/__tests__/transforms/vBind.spec.ts
packages/compiler-vapor/src/generators/prop.ts
packages/runtime-vapor/__tests__/dom/prop.spec.ts
packages/runtime-vapor/src/dom/prop.ts
packages/runtime-vapor/src/index.ts
packages/shared/src/general.ts

compile changes:
- If the attribute is `innerHTML`, use `setHtml` directly.
- If the attribute is `textContent`, use `setText` directly.
- If the attribute is `value` and the element is not `progress` or `custom-element`, use `setValue` directly.
runtime changes:
- Simplify the internal logic of `setDOMProp`.
- Add the `setValue` method.

perf(runtime-vapor): optimize `setDOMProp` on static tag + key
